apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: charts/metrics-server
    repoURL: https://github.com/kubernetes-sigs/metrics-server.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: args[0]
          value: '--metric-resolution=15s'
        - name: args[1]
          value: '--kubelet-insecure-tls'
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
