apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAwJvtrGyC21ddxTXlRRcxLuHmcVDNAIImt5C+A2YZae4lZO8IrUHMfNE2hpS9GjfmcwBqMcg37ZjVZlLRV80EYbW1+vITVHWVcQK6W+JjB1vOfn/+rmx6uEAjJy/jHa9qTVT2RhCH4Sz3BU4S75vN2nf2R2miAWqp4INz4288bzoAjdlsZozoladw9W9DXMFn63OBxx5bKkOJvyHFZgFcICGByA5T7KOaCEweuXlV2pdMTy+Tf67uScR2ODMhr/GazwoihB4hriTPzp0b6uF5X/EbV69uXSzNtor+U3cXT4pYRirUK4ZIqM/CJu5XLVf7jvEaEHgEDrgWTV4C+M0lX6R9Tn/4oSkZDq7Mep/LwOP5ZmY7QouD5PhOYa0ClpzTMVtuP3nVO7GaCsmNQhdBuPfIYvaVU6RlApBqbx7ksH2DHyaj//OUFtatB+Zb5CoTFonMzo1OHgOnsio7B2DHM756ID6Nn1L43gq0gHahYPiCHPJv/QyjQ5b+fEnU7pFjSq2Ldukt2io+e4Tv6atexH9y6c4Wvc/Gn+DF5DNaz2Ov3uSfB5kz2j+OAAGC4uC5PuTGKLvh7EhPt5jR8Pbn37AvBnX4cigWQ0anyzOCD1NoyWh6j38SfD23VtOLDyg8aqIIZh6EdnLfrilCNahv4Tm8XcCXgvIvxSMlvKp14mGygqYx1LeuQN271w189was=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events

